name: Code Climate
on:
  workflow_run:
    workflows:
      - "Test"
    types:
      - completed
jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "16"
      - run: npm ci
      - uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: 364926f5c25fddd78398e0546e35c8e4942783b57b8846ebb0660bf05a066d1d
        with:
          coverageCommand: npm run coverage
          coverageLocations: |
            ${{github.workspace}}/coverage/coverage-final.json:lcov-json
          debug: true
