name: Code Climate
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"
jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 16
    - run: npm ci
    - run: npm run build
    - uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: 364926f5c25fddd78398e0546e35c8e4942783b57b8846ebb0660bf05a066d1d
      with:
        coverageCommand: npm run coverage
        coverageLocations: |
          ${{github.workspace}}/coverage/clover.xml:clover
